version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: copy_local
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped
